# Generated by Django 2.2.9 on 2019-12-30 23:43

from django.db import migrations, models
import django.db.models.deletion
import tehnicka.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predmet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_predmeta', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Predmeti',
            },
        ),
        migrations.CreateModel(
            name='Skola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_skole', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Skole',
            },
        ),
        migrations.CreateModel(
            name='Smjer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_smjera', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Smjerovi',
            },
        ),
        migrations.CreateModel(
            name='Ucenik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=60)),
                ('prezime', models.CharField(max_length=60)),
                ('godina_upisa', models.IntegerField(default=tehnicka.models.current_year)),
                ('skola_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tehnicka.Skola')),
                ('smjer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tehnicka.Smjer')),
            ],
            options={
                'verbose_name_plural': 'Učenici',
            },
        ),
        migrations.CreateModel(
            name='Priznanja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_priznanja', models.CharField(max_length=40)),
                ('bodovi', models.IntegerField(default='0')),
                ('ucenik_id', models.ManyToManyField(to='tehnicka.Ucenik')),
            ],
            options={
                'verbose_name_plural': 'Priznanja',
            },
        ),
        migrations.CreateModel(
            name='Predmet_Ocjena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocjena', models.IntegerField(default='0')),
                ('razred', models.IntegerField(default='6')),
                ('predmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tehnicka.Predmet')),
                ('ucenik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tehnicka.Ucenik')),
            ],
        ),
        migrations.AddField(
            model_name='predmet',
            name='ocjene_ucenika',
            field=models.ManyToManyField(through='tehnicka.Predmet_Ocjena', to='tehnicka.Ucenik'),
        ),
        migrations.CreateModel(
            name='Kljucni_Predmeti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_pr', models.CharField(max_length=40)),
                ('smjer', models.ManyToManyField(to='tehnicka.Smjer')),
            ],
        ),
    ]
