# Generated by Django 2.2.9 on 2020-01-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tehnicka', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Razred',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_razreda', models.CharField(max_length=50)),
                ('broj_razreda', models.IntegerField(default='6')),
                ('predmet', models.ManyToManyField(to='tehnicka.Predmet')),
            ],
        ),
    ]
