# Generated by Django 2.2.9 on 2020-01-02 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tehnicka', '0002_razred'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predmet_ocjena',
            options={'verbose_name_plural': 'Ocjene iz predmeta'},
        ),
        migrations.RemoveField(
            model_name='ucenik',
            name='smjer_id',
        ),
    ]
