# Generated by Django 2.2.9 on 2020-01-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tehnicka', '0003_auto_20200102_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucenik',
            name='smjer',
            field=models.ManyToManyField(to='tehnicka.Smjer'),
        ),
    ]
